sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_690b6862c83b_key -iv $encrypted_690b6862c83b_iv -in multi-k8s-386207-d5721670853b.json.enc -out multi-k8s-386207-d5721670853b.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gloud components update kubectl
  - gcloud  auth activate-service-account --key-file service-account.json
